name = "SphericalSplines"
uuid = "3bde4124-ddb3-11e8-1e08-e37fcff744c7"
authors = ["Olli Wilkman <olli.wilkman@iki.fi>"]
version = "0.5"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1.0"
