name = "SphericalSplines"
uuid = "3bde4124-ddb3-11e8-1e08-e37fcff744c7"
authors = ["Olli Wilkman <olli.wilkman@iki.fi>"]
version = "0.1.0"

[deps]
GSL = "92c85e6c-cbff-5e0c-80f7-495c94daaecd"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
